---
- name: Install php debian
  apt:
    name: "{{ php_packages }}"
    install_recommends: false
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install php centos
  yum:
    name: "{{ php_packages }}"
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
