---
# tasks file for networking
- name: Install networking packages debian
  apt:
    name: "{{ networking_packages_debian }}"
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Ensure firewalld is stopped and disabled
  service: name=firewalld state=stopped enabled=no
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  failed_when: false

- name:  Install networking packages centos
  yum:
    name: "{{ networking_packages_centos }}"
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Enable service centos
  systemd:
    name: iptables
    state: started
    enabled: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Allow new incoming connection on TCP port 80
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 80
    ctstate: NEW
    jump: ACCEPT
    rule_num: 2
    comment: Accept new HTTP connections
  #when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# - name: add rules for centos
#   shell: |
#     iptables -I INPUT -p tcp -m tcp --dport 80 -j ACCEPT
#     iptables -I INPUT -p tcp -m tcp --dport 443 -j ACCEPT
#   when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Save current state of the firewall in system file debian
  shell: |
    iptables-save > /etc/iptables/rules.v4
    ip6tables-save > /etc/iptables/rules.v6
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Save current state of the firewall in system file centos
  shell: |
    iptables-save > /etc/sysconfig/iptables
    ip6tables-save > /etc/sysconfig/ip6tables
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: restart iptables service
  systemd:
    name: iptables
    state: restarted

- name: Reboot a centos machine to apply selinux disable policy
  ansible.builtin.reboot:
    reboot_timeout: 140
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
